### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by Alex1-ai**
#### Type of change

Documentation

#### What does this implement/fix?

I have made updates to the Code-Of-Conduct.md file. This file serves as a guideline that ensures an appropriate code of conduct, applicable to everyone involved in the project.

#### Additional information

The changes made to the Code-Of-Conduct.md file include clarifications, updates, and improvements to ensure inclusivity, respectful communication, and a positive community atmosphere within the project. These changes aim to foster collaboration, encourage diversity, and maintain a safe and welcoming environment for all contributors and participants.

### CODE REVIEW

**Comment by Alex1-ai** [comment]
@sampan501 I just added a code of conduct to the insight. please do well to check it up if it is OK. Thanks

**Comment by sampan501** [comment]
Thank you for this contribution, this is very valuable. Could you also change the current link to the contribution guidelines on the documentation website? That should involve adding a `code_of_conduct.rst` file to the [docs/development](https://github.com/neurodata/hyppo/tree/main/docs/development) folder and then adding the reference to the file in `index.rst` within that folder. A good example of what to do is the [contributing.rst file](https://github.com/neurodata/hyppo/blob/main/docs/development/contributing.rst)

**Comment by sampan501** [comment]
@all-contributors please add @Alex1-ai  for documentation

**Comment by sampan501** [comment]
@all-contributors please add @Alex1-ai for documentation

**Comment by Alex1-ai** [comment]
> @all-contributors please add @Alex1-ai for documentation

Thank you , really appreciate

**Comment by Alex1-ai** [comment]
> @Alex1-ai
> 
> @Alex1-ai already contributed before to doc

Yes but it has not been merged still open sir

**Comment by Alex1-ai** [comment]
> Thank you for this contribution, this is very valuable. Could you also change the current link to the contribution guidelines on the documentation website? That should involve adding a `code_of_conduct.rst` file to the [docs/development](https://github.com/neurodata/hyppo/tree/main/docs/development) folder and then adding the reference to the file in `index.rst` within that folder. A good example of what to do is the [contributing.rst file](https://github.com/neurodata/hyppo/blob/main/docs/development/contributing.rst)

Ok sir, I would work on it straight away

**Comment by Alex1-ai** [comment]
@sampan501 Good day sir, Done what you requested and have open another pull request . I would appreciate feedback. Thanks

**Pull request merged**
