### PR TITLE
Fix #228

### LINKED ISSUE #228: Reproducibility of tests not fully functional
Seems that we still do not get consistent reproducibility after #212, I think it has something to do with [PermGroups](https://github.com/neurodata/hyppo/blob/771bda8f029f95073613bed18709d80d90ef3a2d/hyppo/tools/common.py#L346) but I do not quite understand its behavior.

### PR DESCRIPTION
**Pull request by rflperry**
Adds `rng.permutation` reproducibility to `perm_test` @kareef928 from issue #228 . Should all work, but someone can PR to this or extend the modifications.

### CODE REVIEW

**Comment by rflperry** [comment]
Dunno what the error is about but otherwise seems fine.

**Comment by bdpedigo** [comment]
when I was looking at this code, I felt like it'd be simpler (fewer conditional statements) to just always call `permuter`, since `_PermGroups` already has a use case for permuting the entire dataset when no groups are given. Does that make sense?

**Comment by rflperry** [comment]
Yeah I think there's a simpler MVP, but I don't think the error being thrown should be a result of my changes rather something else. Otherwise I can revert to the MVP that removes the addition of `rng` being passed into the `_PermGroups`.

**Comment by sampan501** [comment]
I looked through the changes and there shouldn't be this much of a difference in the p-value. This test at least is off by nearly 0.001

**Comment by sampan501** [comment]
I think the problem is related to the way p-values are computed in MGC scipy, which have not been fixed yet. I think it's fine to merge these changes and I'll make a PR to fix scipy MGC p-values

**Comment by rflperry** [comment]
Okay. I was just looking through and my only guess was that some how the np.random.seed defined in the test code was no longer setting the seed but since the pvalue remained the same across test runs there was still clearly a seed. At best I was going to revert to something that wouldn't affect anything and see if the test passed.

**Pull request merged**
