### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by rudra-code-creator**
Can't this all be simplified to a singular import statement

### CODE REVIEW

**Comment by sampan501** [comment]
Hi, this cannot be simplified into a single import statement. Doing it this way is necessary to get the relative imports working

**Comment by rudra-code-creator** [comment]
What about 

from hyppo import *

**Comment by sampan501** [comment]
There's a number of reasons that using star imports in general are a bad idea because of code readability, unintentional imports, etc. Also it won't work in this case

**Comment by sampan501** [comment]
I've yet to see the point of changing this. Simplifying these import statements don't add any benefits for the code base

**Pull request closed without merging**
