### PR TITLE
Switch to MIT license

### LINKED ISSUE #194: switch to MIT license
My issue is about ...

### PR DESCRIPTION
**Pull request by PSSF23**
#### Reference issue

Close #194 
#### Type of change

Documentation
#### What does this implement/fix?

Switch to MIT license with year: 2019 and holder name: Neurodata 
#### Additional information

None

### CODE REVIEW

**Comment by sampan501** [comment]
yes we should move to MIT. It's a simpler and fairly permissive liscence

**Review by PSSF23 — COMMENTED** [review]
@sampan501 The switch should be done!

**Comment by sampan501** [comment]
Can you also change it on the documentation website [here](https://github.com/neurodata/hyppo/blob/main/docs/license.rst)? Thanks!

**Review by PSSF23 — COMMENTED** [review]
@sampan501 updated!

**Pull request merged**
