### PR TITLE
Add independence range to docs

### PR DESCRIPTION
**Pull request by oakla**
#### Reference issue
Closes issues #329

#### Type of change
Documentation

#### What does this implement/fix?
A small amendment to a previous PR closing the same issue (#329)

#### Additional information
Changes are largely cosmetic

### CODE REVIEW

**Comment by oakla** [comment]
Is the code coverage check a true blocker? The only changes were to documentation. If someone can confirm that this check is truly relevant, I can investigate further.

**Comment by sampan501** [comment]
Hi, we no longer use the dev branch to compare commits, we use main. This branch is a bit outdated so you will need to merge  main changes into it and resolve conflicts before I can merge

**Comment by oakla** [comment]
This PR is now redundant and is replaced by #415

**Comment by oakla** [comment]
This PR is now redundant and is replaced by #415

**Pull request closed without merging**
