### PR TITLE
Add code of conduct to documentation website

### PR DESCRIPTION
**Pull request by Alex1-ai**
#### Type of change
Please specify the type of change you are proposing:
- Bug Fix
- Documentation Update
- Feature Request

#### What does this implement/fix?
Please explain your changes.

I have updated the link to the contribution guidelines on the documentation website. 
This involved adding a new `code_of_conduct.rst` file to the `docs/development` folder 
and referencing it in the `index.rst` file within that folder. The `code_of_conduct.rst` 
file contains the content of the code of conduct in reStructuredText format.

These changes ensure that users can easily access and read our project's code of conduct 
when they visit the development documentation.

### CODE REVIEW

**Comment by Alex1-ai** [comment]
@sampan501 Please review the changes . Thanks

**Review by sampan501 — CHANGES_REQUESTED** [review]
Guidelines aren't currently showing up on the website

**Comment by sampan501** [comment]
I think you need to update your fork, and then link to the file correctly like the license and other files do

**Comment by Alex1-ai** [comment]
@sampan501 Thanks for your feedback made the correction

**Review by sampan501 — APPROVED** [review]

**Comment by Alex1-ai** [comment]
@sampan501 Thanks

**Pull request merged**
