### PR TITLE
Redundancy check for MGC

### LINKED ISSUE #125: Add warning when X or Y have redundant rows
When `X` or `Y` have redundant rows using `MGC`, the optimal scale will throw away redundant entries more or less (which makes sense), but this isn't immediately obvious reading through the output, and reduces the interpretability of the optimal scale. For example, if I have a perfectly linear relationship with two length 10 vectors `X` and `Y` where `xi = yi` for all `i`, I will get an optimal scale of `5` if there are `5` redundant entries. This may shift how I am otherwise interpreting the optimal scale returned. It may be advisable to either throw a warning telling people that they have redundant rows in `X`, `Y`, or both (and if `X` or `Y` are a distance matrix, this would translate to two elements with distances between them of exactly `0`) and remove these entries for them, or throw an error and tell people to do it themselves.

#### Reproducing code example:

```
from hyppo.independence import MGC as mgc_test
import numpy as np

X = np.hstack((np.arange(0, 6), 5, 5, 5, 5))
Y = np.hstack((np.arange(0, 6), 5, 5, 5, 5))

print(len(X))
>> 10
print(len(Y))
>> 10
```
and when we run `MGC`:
```
stat, pval, mgc_map = mgc_test().test(X, Y)
print(stat)
>> 1
print(pval)
>> .002
print(mgc_map["opt_scale"])
>> [6, 6]
```
If the user is not careful, they may interpret this to mean the relationship between `X` and `Y` is not linear, though that would be false since the optimal scale is not `[10, 10]` exclusively due to the redundancies. TL; DR is the upper bound for the `X` and `Y` scales (to my knowledge) will be the numbers of unique rows in each matrix (or the number of unique points which do not share a distance of zero between one another), and should probably be interpreted in that context.

#### Version information

- OS: Ubuntu 20.04
- Python Version 3.7.8
- Package Version 0.1.2

### PR DESCRIPTION
**Pull request by Verathagnus**
#### Reference issue

 Add warning when X or Y have redundant rows; close #125 
#### Type of change

Documentation
#### What does this implement/fix?

Added a function _check_redundancy in mgc.py to check if redundancies are present in x or y and report a warning to the user.
#### Additional information

I used the following code to find if redundant rows exist
```
    def _check_redundancy(self, x, y, mgc_dict):
        """Check if there are redundant rows in input arrays x and y"""
        if x.shape[0] == 1:
            return

        if [len(x), len(y)] > mgc_dict["opt_scale"]:
            warnings.warn("Redundant rows exist")
```

Added a test in test_mgc.py for checking if UserWarning is printed successfully.

### CODE REVIEW

**Comment by Verathagnus** [comment]
Thank you for pointing out my mistake. I'll correct it.

**Comment by Verathagnus** [comment]
Done. There are too many commits but not much changes from the main repo. Should I create a new fork and then add just the changed files?

**Comment by sampan501** [comment]
@Verathagnus Few things:

- Adding the commit message "Add files via upload" tells me nothing about the changes that were done and makes it harder for me to review the PR
- `if x.shape[0] == 1` is not a possible case, since the test will not run under 5 samples
- `if [len(x), len(y)] > mgc_dict["opt_scale"]` is not the correct logic needed to throw this warning. The optimal scale is only equal to the global scale (in your case `[len(x), len(y)]` when the relationship is linear and there are no duplicate rows. The current logic will throw a warning when the dependency relationship is nonlinear

Looking through the commits, it is a little difficult to follow what all was done (code disappeared, reappeared, files were duplicated, etc.). I would go through, and cherry-pick the commits that are off or restart with a clean branch.

**Comment by Verathagnus** [comment]
First, I tried using a dictionary(or set) to check for duplicate rows but it caused issue with tests
``` 
def _check_redundancy(self, x, y):
        """Check if there are redundant rows in input arrays x and y"""
        redundancy_check_dict = dict()
        redundancy_flag = False
        for i in zip(x, y):
            if str(i) in redundancy_check_dict:
                redundancy_flag = True
                break
            else:
                redundancy_check_dict[str(i)] = 1

        if redundancy_flag:
            warnings.warn("Redundant rows exist")
```

Next I tried this
```
        combined = [(x[i], y[i]) for i in range(x.shape[0])]
        unique_rows = set(combined)
        redundancy_flag = len(combined) != len(unique_rows)
        if redundancy_flag:
            warnings.warn("Redundant rows exist")
```
This one also caused issues in the tests.
I'm not sure what was wrong. Could you please check?

**Comment by sampan501** [comment]
I believe this fix should be about a 1 line check of inputs `X` and `Y`, something using `np.unique`

**Comment by Verathagnus** [comment]
I tried with that as well previously but there was a test in which it came out wrong.
```
combined = np.vstack([X, Y]).T
unique_rows = np.unique(combined, axis=0)
```
I placed the check_redundancy call before the check_input call previously during that test. That may have caused the issue. I'll try that again this time.

**Comment by sampan501** [comment]
yes it should be after

**Comment by Verathagnus** [comment]
https://github.com/neurodata/hyppo/pull/220
Please check this. I have started from fresh and it generated a new PR on contributing.

**Pull request closed without merging**
