### PR TITLE
ENH Optimize tree posteriors & wall time

### PR DESCRIPTION
**Pull request by PSSF23**

### CODE REVIEW

**Review by PSSF23 — COMMENTED** [review]
Let me know if you see anywhere that can be optimized

**Review by PSSF23 — COMMENTED** [review]
Bottleneck seems to be the tree initialization. After fixing it I'll start moving stuff to `sktree`.

**Review by sampan501 — CHANGES_REQUESTED** [review]
Once you add a unit test, I think we should be good

**Review by PSSF23 — COMMENTED** [review]
TODO: test both implementations on the same posteriors

**Pull request closed without merging**
